spring:
  application:
    name: decision-service
  profiles:
    active: development

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/decision
    username: postgres
    password: admin@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  cloud:
    function:
      definition: processCustomerCreated
    stream:
      kafka:
        bindings:
          processCustomerCreated-in-0:
            consumer:
              enable-dlq: true
      bindings:
        processCustomerCreated-in-0:
          group: decision-microservice
          consumer:
            max-attempts: 5
            back-off-initial-interval: 6500
            back-off-multiplier: 4
            back-off-max-interval: 10000
          destination: customer-topic

        processCustomerCreated-out-0:
          destination: decision-topic



logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug

server:
  port: 9021
