spring:
  application:
    name: decision-service
  profiles:
    active: development

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/decision
    username: postgres
    password: admin@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  cloud:
    function:
      definition: handleCustomerCreated
    stream:
      bindings:
        handleCustomerCreated-in-0:
                          destination: customer-topic
                          group: decision-microservice

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug

server:
  port: 9021
